config/routes.rb
Rails.application.routes.draw do
  root 'temp#root'

  devise_for :users

  resources :activity_logs, only: [:new, :create, :show, :destroy, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity_log.rb
# Responsible for modeling an activity that is logged by a user, contains such information as who logged the activity, what the activity was, and when it was started and ended.
class ActivityLog < ApplicationRecord
  belongs_to :user
  validates_presence_of :ended_at, :started_at, :label, :user

  # Check if activity log belongs to owner of activity log.
  def belongs_to?(user)
    self.user == user
  end #TT
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# Devise generated user model. Most other models and resources can only be accessed in relationship with a specific user object so that the application can be used in relationship with multiple real human users.
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :activity_logs

  # Save an activity log for the specified user.
  def save_activity_log(activity_log)
    activity_log.user = self
    activity_log.save
  end #TT
end

app/controllers/activity_logs_controller.rb
# Responsible for collecting information and rendering views for the basic activity log actions including new, show, edit, create, update, and destroy.
class ActivityLogsController < ApplicationController
  before_action :authenticate_user!

  before_action :only_allow_owner!, only: [
    :show, :edit, :update, :destroy
  ]

  def new
    @activity_log = new_activity_log
  end

  def show
    @activity_log = current_activity_log
  end

  def edit
    @activity_log = current_activity_log
  end

  def create
    @activity_log = new_activity_log(with: activity_log_params)

    respond_to do |format|
      if current_user.save_activity_log(@activity_log)
        format.html do
          redirect_to @activity_log, notice: 'Activity log was successfully created.'
        end
      else
        format.html do
          render :new
        end
      end
    end
  end

  def update
    @activity_log = current_activity_log

    respond_to do |format|
      if @activity_log.update(activity_log_params)
        format.html do
          redirect_to @activity_log, notice: 'Activity log was successfully updated.'
        end
      else
        format.html do
          render :edit
        end
      end
    end
  end

  def destroy
    @activity_log = current_activity_log

    @activity_log.destroy
    respond_to do |format|
      format.html do
        redirect_to root_path, notice: "Activity log was successfully deleted"
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def activity_log_params
    params.require(:activity_log).permit(:started_at, :ended_at, :label)
  end

  # Check that current user is owner of activity log or redirect somewhere else.
  def only_allow_owner!
    unless current_activity_log.belongs_to? current_user
      redirect_to root_path
    end
  end

  # Return current activity log based on the URL.
  def current_activity_log
    ActivityLog.find(params[:id])
  end

  # Create a new activity log with optional starting attributes.
  def new_activity_log(with: {})
    ActivityLog.new(with)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/temp_controller.rb
# This is a temporary controller, only to be used until actual controllers and routes are setup.
class TempController < ApplicationController
  def root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activity_logs/edit.html.erb
Edit Activity Log

<%= form_for @activity_log do |form| %>
  <% if @activity_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_log.errors.count, "error") %> prohibited this prompt from being saved:</h2>

      <ul>
      <% @activity_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.text_field :started_at %>
  </div>

  <div class="field">
    <%= form.label :ended_at %>
    <%= form.text_field :ended_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activity_logs/new.html.erb
New Activity Log

<%= form_for @activity_log do |form| %>
  <% if @activity_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_log.errors.count, "error") %> prohibited this prompt from being saved:</h2>

      <ul>
      <% @activity_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.text_field :started_at %>
  </div>

  <div class="field">
    <%= form.label :ended_at %>
    <%= form.text_field :ended_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activity_logs/show.html.erb
<%= @activity_log.started_at %> |
<%= @activity_log.ended_at %> |
<%= @activity_log.label %> |
<%= link_to("Update", edit_activity_log_path(@activity_log)) %> |
<%= link_to("Delete", @activity_log, data: { confirm: "Are you sure?" }, method: :delete, id: "delete_activity_log") %>

app/views/layouts/_primary_nav.html.erb
<nav id="primary_nav">
  <ul>
    <% if current_user %>
      <%= link_to "Delete Account", user_registration_path, data: { confirm: "Are you sure?" }, method: :delete, id: :delete_account_link %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourteenForty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <%= render "layouts/primary_nav" %>
    <%= yield %>
  </body>
</html>

app/views/temp/root.html.erb
<h1>Welcome to 1440</h1>
<p>Website under construction. Come back soon!</p>